In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

Проверка расстояния между питами

In [2]:
CD_distances_data = pd.read_csv("CD/distances.csv")
CD_distances_data.head()

   Δx [nm]     Δy [nm]  φ [deg]      R [nm]    Δz [nm]
0      0.0  669.421488    -90.0  669.421488  14.479873
1      0.0  528.925620    -90.0  528.925620   8.864662
2      0.0  570.247934    -90.0  570.247934  -0.371138
3      0.0  454.545455    -90.0  454.545455  -9.407720
4      0.0  404.958678    -90.0  404.958678   1.941820

In [15]:
R = CD_distances_data["R [nm]"][1:] # Выкинули первую точку, потому что не попадает в 3 сигма

sigma_instrumental = 10*5 # 3 цены деления в нм
sigma_std = np.sqrt(np.std(R, ddof=1))

sigma = np.sqrt(
    sigma_std**2 + sigma_instrumental ** 2
)

print(f"Случайная погрешность измерения: {sigma_std}")
print(f"d = {np.mean(R):.0f} +- {sigma:.0f} нм")

Случайная погрешность измерения: 8.300331363163941
d = 492 +- 51 нм

Считаем ширину

In [26]:
CD_width_data = pd.read_csv("CD/widths.csv")
CD_width_data.head()

      Δx [nm]  Δy [nm]  φ [deg]      R [nm]   Δz [nm]
0  206.611570      0.0      0.0  206.611570  9.301712
1  198.347107      0.0      0.0  198.347107 -3.024729
2  231.404959      0.0      0.0  231.404959 -4.575065
3  168.224299      0.0      0.0  168.224299 -4.276944
4  242.990654      0.0      0.0  242.990654  5.955004

In [29]:
w = CD_width_data["R [nm]"] # Выкинули первую точку, потому что не попадает в 3 сигма

sigma_instrumental = 10*5 # 3 цены деления в нм
sigma_std = np.sqrt(np.std(w, ddof=1))

sigma = np.sqrt(
    sigma_std**2 + sigma_instrumental ** 2
)

print(f"Случайная погрешность измерения: {sigma_std:.0f}")
print(f"w = {np.mean(w):.0f} +- {sigma:.0f} нм")

Случайная погрешность измерения: 5
w = 206 +- 50 нм

Расстояние между треками

In [30]:
CD_tracks_data = pd.read_csv("CD/track_distances.csv")
CD_tracks_data.head()

      Δx [nm]  Δy [nm]  φ [deg]      R [nm]   Δz [nm]
0  336.448598      0.0      0.0  336.448598 -2.276874
1  280.373832      0.0      0.0  280.373832  4.059188
2  311.526480      0.0      0.0  311.526480  0.068628
3  342.679128      0.0      0.0  342.679128  6.109674
4  348.909657      0.0      0.0  348.909657 -8.710572

In [31]:
d_tracks = CD_tracks_data["R [nm]"] # Выкинули первую точку, потому что не попадает в 3 сигма

sigma_instrumental = 10*5 # 3 цены деления в нм
sigma_std = np.sqrt(np.std(d_tracks, ddof=1))

sigma = np.sqrt(
    sigma_std**2 + sigma_instrumental ** 2
)

print(f"Случайная погрешность измерения: {sigma_std:.0f}")
print(f"w = {np.mean(d_tracks):.0f} +- {sigma:.0f} нм")

Случайная погрешность измерения: 6
w = 295 +- 50 нм

Длины питов на диске

In [36]:
CD_lengths_data = pd.read_csv("CD/lengths.csv")
CD_lengths_data.head()

   Δx [nm]      Δy [nm]  φ [deg]       R [nm]    Δz [nm]
0      0.0  1024.793388    -90.0  1024.793388   5.438299
1      0.0   826.446281    -90.0   826.446281  21.714320
2      0.0   909.090909    -90.0   909.090909  -0.198350
3      0.0   570.247934    -90.0   570.247934  -8.540021
4      0.0   338.842975    -90.0   338.842975   0.280776

In [38]:
print(f"l_min = {min(CD_lengths_data["R [nm]"])}")
print(f"l_max = {max(CD_lengths_data["R [nm]"])}")

l_min = 264.46280992
l_max = 1024.79338843

Периоды TGT

In [33]:
tgt_periods = pd.read_csv("TGT/periods.csv")
tgt_periods

      Δx [nm]       Δy [nm]    φ [deg]        R [nm]     Δz [nm]  n_periods
0    0.000000   6803.738318 -90.000000   6803.738318  -50.812243          4
1    0.000000  10354.101765 -90.000000  10354.101765 -192.302624          6
2    0.000000 -12190.031153  90.000000  12190.031153  145.653304          7
3 -107.995846  10259.605400 -90.603091  10260.173783  -43.169034          6

In [34]:
tgt_periods["periods"] = tgt_periods["R [nm]"] / tgt_periods["n_periods"]
tgt_periods

,Δx [nm],Δy [nm],φ [deg],R [nm],Δz [nm],n_periods,periods
0,0.000000,6803.738318,-90.000000,6803.738318,-50.812243,4,1700.934579
1,0.000000,10354.101765,-90.000000,10354.101765,-192.302624,6,1725.683628
2,0.000000,-12190.031153,90.000000,12190.031153,145.653304,7,1741.433022
3,-107.995846,10259.605400,-90.603091,10260.173783,-43.169034,6,1710.028964

In [35]:
sigma_instrumental = 10*5 # 3 цены деления в нм
sigma_std = np.sqrt(np.std(tgt_periods["periods"], ddof=1))

sigma = np.sqrt(
    sigma_std**2 + sigma_instrumental ** 2
)


print(f"T = {np.mean(tgt_periods["periods"]):.0f} +- {sigma:.0f} нм")

T = 1720 +- 50 нм